#! /bin/bash
#
# /etc/init.d/apicall
#
### BEGIN INIT INFO
# Provides:          apicall
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable services provided by daemon.
### END INIT INFO


case "$1" in
  start)
    # Start the daemon 
    if [ "`ps -ef| grep /usr/share/apicall/apicall.py  | wc -l`" -eq "2" ] ; then
      echo "service is already running"
    else
      echo "starting server"
      python /usr/share/apicall/apicall.py start
    fi
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    python /usr/share/apicall/apicall.py stop
    ;;
  status)
    if [ "`ps -ef| grep /usr/share/apicall/apicall.py  | wc -l`" -eq "2" ] ; then
      echo "APICALL Service is Running"
    else
      echo "APICALL Service is stopped"
    fi
    ;;
  restart)
    if [ "`ps -ef| grep /usr/share/apicall/apicall.py  | wc -l`" -eq "2" ] ; then
       echo "Restarting server"
       python /usr/share/apicall/apicall.py restart
    else
       python /usr/share/apicall/apicall.py start
    fi
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/apicall.sh {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

